CREATE TABLE USUARIOS(
 ID_USUARIO SMALLINT AUTO_INCREMENT PRIMARY KEY,
 NOME VARCHAR(120),
 EMAIL VARCHAR(75),
 IDADE NUMERIC(15)
);

INSERT INTO USUARIOS(
NOME, EMAIL, IDADE
)
VALUES ('VINICIUS','VINICIUS@EMAIL.COM.BR',30)
      ,('BRUNA','BRUNA@EMAIL.COM.BR',26)
      ,('MAURICIO','MAURICIO@EMAIL.COM.BR',28)
      ,('CHIGRININZ','CHIGRININZ@EMAIL.COM.BR',41)

DELETE 
  FROM USUARIOS
 WHERE ID_USUARIO = 4

 UPDATE USUARIOS
   SET NOME = 'MAURICITO'
 WHERE ID_USUARIO = 3
